In [39]:
import pandas as pd
from sklearn.impute import SimpleImputer

df = pd.read_csv('Salaries.csv')

C:\Users\Administrator\AppData\Local\Temp\ipykernel_13892\992393571.py:4: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Salaries.csv')

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
df = pd.read_csv('dataset_traffic_accident_prediction1.csv')

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 840 entries, 0 to 839
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Weather               798 non-null    object
 1   Road_Type             798 non-null    object
 2   Time_of_Day           798 non-null    object
 3   Traffic_Density       798 non-null    float64
 4   Speed_Limit           798 non-null    float64
 5   Number_of_Vehicles    798 non-null    float64
 6   Driver_Alcohol        798 non-null    float64
 7   Accident_Severity     798 non-null    object
 8   Road_Condition        798 non-null    object
 9   Vehicle_Type          798 non-null    object
 10  Driver_Age            798 non-null    float64
 11  Driver_Experience     798 non-null    float64
 12  Road_Light_Condition  798 non-null    object
 13  Accident              798 non-null    float64
dtypes: float64(7), object(7)
memory usage: 92.0+ KB

In [44]:
df.head()

,Weather,Road_Type,Time_of_Day,Traffic_Density,Speed_Limit,Number_of_Vehicles,Driver_Alcohol,Accident_Severity,Road_Condition,Vehicle_Type,Driver_Age,Driver_Experience,Road_Light_Condition,Accident
0,Rainy,City Road,Morning,1.0,100.0,5.0,0.0,NaN,Wet,Car,51.0,48.0,Artificial Light,0.0
1,Clear,Rural Road,Night,NaN,120.0,3.0,0.0,Moderate,Wet,Truck,49.0,43.0,Artificial Light,0.0
2,Rainy,Highway,Evening,1.0,60.0,4.0,0.0,Low,Icy,Car,54.0,52.0,Artificial Light,0.0
3,Clear,City Road,Afternoon,2.0,60.0,3.0,0.0,Low,Under Construction,Bus,34.0,31.0,Daylight,0.0
4,Rainy,Highway,Morning,1.0,195.0,11.0,0.0,Low,Dry,Car,62.0,55.0,Artificial Light,1.0

In [45]:
df = df.dropna(subset=['Accident'])

In [46]:
df.head()

,Weather,Road_Type,Time_of_Day,Traffic_Density,Speed_Limit,Number_of_Vehicles,Driver_Alcohol,Accident_Severity,Road_Condition,Vehicle_Type,Driver_Age,Driver_Experience,Road_Light_Condition,Accident
0,Rainy,City Road,Morning,1.0,100.0,5.0,0.0,NaN,Wet,Car,51.0,48.0,Artificial Light,0.0
1,Clear,Rural Road,Night,NaN,120.0,3.0,0.0,Moderate,Wet,Truck,49.0,43.0,Artificial Light,0.0
2,Rainy,Highway,Evening,1.0,60.0,4.0,0.0,Low,Icy,Car,54.0,52.0,Artificial Light,0.0
3,Clear,City Road,Afternoon,2.0,60.0,3.0,0.0,Low,Under Construction,Bus,34.0,31.0,Daylight,0.0
4,Rainy,Highway,Morning,1.0,195.0,11.0,0.0,Low,Dry,Car,62.0,55.0,Artificial Light,1.0

In [47]:
X = df.drop('Accident',axis=1)
y = df['Accident']

In [57]:
xtrain,xtest,ytrain,ytest = train_test_split(X,y,train_size=0.8,random_state=42)

In [58]:
obj_cols = xtrain.select_dtypes(include='object').columns

In [59]:
obj_cols

Index(['Weather', 'Road_Type', 'Time_of_Day', 'Accident_Severity',
       'Road_Condition', 'Vehicle_Type', 'Road_Light_Condition'],
      dtype='object')

In [62]:
impute = SimpleImputer(strategy="most_frequent")
# impute = SimpleImputer(strategy="constant",fill_value=0)

xtrain[obj_cols] = impute.fit_transform(xtrain[obj_cols])

In [67]:
xtrain.isnull().sum()

Weather                  0
Road_Type                0
Time_of_Day              0
Traffic_Density         36
Speed_Limit             33
Number_of_Vehicles      31
Driver_Alcohol          34
Accident_Severity        0
Road_Condition           0
Vehicle_Type             0
Driver_Age              31
Driver_Experience       34
Road_Light_Condition     0
dtype: int64

In [63]:
impute.statistics_

array(['Clear', 'Highway', 'Afternoon', 'Low', 'Dry', 'Car',
       'Artificial Light'], dtype=object)

In [65]:
xtest[obj_cols] = impute.transform(xtest[obj_cols])

In [55]:
xtest

,Weather,Road_Type,Time_of_Day,Traffic_Density,Speed_Limit,Number_of_Vehicles,Driver_Alcohol,Accident_Severity,Road_Condition,Vehicle_Type,Driver_Age,Driver_Experience,Road_Light_Condition
726,Rainy,City Road,Morning,2.0,50.0,4.0,0.0,Low,Dry,Car,58.0,58.0,Daylight
696,Clear,Highway,Morning,2.0,60.0,5.0,0.0,Low,Wet,Motorcycle,42.0,39.0,Daylight
65,Clear,Highway,Afternoon,1.0,80.0,3.0,1.0,Low,Dry,Car,56.0,48.0,No Light
558,Snowy,Highway,Night,0.0,100.0,2.0,0.0,Moderate,Dry,Car,40.0,40.0,Daylight
68,Clear,Highway,Afternoon,2.0,80.0,3.0,0.0,Low,Dry,Car,52.0,43.0,Artificial Light
...,...,...,...,...,...,...,...,...,...,...,...,...,...
618,Clear,City Road,Morning,1.0,100.0,4.0,NaN,Low,Icy,Car,53.0,48.0,Artificial Light
838,Foggy,Highway,Afternoon,2.0,60.0,3.0,0.0,Low,Dry,Car,25.0,19.0,Artificial Light
782,Clear,Rural Road,Afternoon,0.0,80.0,5.0,0.0,Moderate,Icy,Car,NaN,NaN,No Light
538,Clear,City Road,Morning,1.0,60.0,3.0,0.0,Moderate,Dry,Truck,23.0,14.0,Daylight
699,Clear,City Road,Evening,0.0,100.0,NaN,1.0,Low,Dry,Truck,47.0,40.0,Daylight

In [ ]:
impute.get_feature_names_out()

array(['Weather', 'Road_Type', 'Time_of_Day', 'Accident_Severity',
       'Road_Condition', 'Vehicle_Type', 'Road_Light_Condition'],
      dtype=object)

In [ ]:
new = pd.DataFrame(objdf,columns=impute.get_feature_names_out())
new.info("")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 638 entries, 0 to 637
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Weather               638 non-null    object
 1   Road_Type             638 non-null    object
 2   Time_of_Day           638 non-null    object
 3   Accident_Severity     638 non-null    object
 4   Road_Condition        638 non-null    object
 5   Vehicle_Type          638 non-null    object
 6   Road_Light_Condition  638 non-null    object
dtypes: object(7)
memory usage: 35.0+ KB

In [ ]:
objdf

array([['Rainy', 'Rural Road', 'Evening', ..., 'Wet', 'Car',
        'Artificial Light'],
       ['Rainy', 'Highway', 'Afternoon', ..., 'Dry', 'Car', 'Daylight'],
       ['Clear', 'Highway', 'Afternoon', ..., 'Wet', 'Car', 0],
       ...,
       ['Rainy', 'Mountain Road', 'Morning', ..., 'Dry', 'Car',
        'Artificial Light'],
       ['Clear', 'Rural Road', 'Evening', ..., 'Under Construction',
        'Car', 'Artificial Light'],
       ['Rainy', 'Highway', 'Afternoon', ..., 'Under Construction',
        'Car', 'Daylight']], shape=(638, 7), dtype=object)